newrelic/nri-apache

CONTRIBUTING.md, README.md
Add contributing information as appears in the infra-integrations repository
=> Contributing info

README.md
=> Test Jenkins PR 1x1x1

README.md
=> Revert "Test Jenkins PR 1x1x1"

CHANGELOG.md, Makefile, src/inventory.go, src/inventory_test.go
This fixes: `slice bounds out of range error` 
https://play.golang.org/p/MB8UqSnQkCK
=> Fix getModules slice bound issue

CHANGELOG.md
=> Changelog 1.1.2

.papers_config.yml, papers_manifest.yml
=> Adding papers-go license detection

Makefile, src/apache.go, src/inventory.go, src/inventory_test.go, src/metrics.go, src/metrics_test.go, vendor/github.com/newrelic/infra-integrations-sdk/args/args.go, vendor/github.com/newrelic/infra-integrations-sdk/args/json.go, vendor/github.com/newrelic/infra-integrations-sdk/data/event/event.go, vendor/github.com/newrelic/infra-integrations-sdk/data/inventory/inventory.go, vendor/github.com/newrelic/infra-integrations-sdk/data/metric/metrics.go, vendor/github.com/newrelic/infra-integrations-sdk/data/metric/set_marshal.go, vendor/github.com/newrelic/infra-integrations-sdk/data/metric/source_type.go, vendor/github.com/newrelic/infra-integrations-sdk/integration/entity.go, vendor/github.com/newrelic/infra-integrations-sdk/integration/integration.go, vendor/github.com/newrelic/infra-integrations-sdk/integration/options.go, vendor/github.com/newrelic/infra-integrations-sdk/log/log.go, vendor/github.com/newrelic/infra-integrations-sdk/persist/storer.go, vendor/vendor.json
=> Upgrade to V3 SDK

src/inventory_test.go
renamed inventory package naming
=> IHOST-1625 renaming inventory package

apache-config.yml.sample, src/apache.go
This PR will fix the default value for remote monitoring flag
=> fixed default value for remote monitoring

src/apache.go, src/apache_test.go
Added backwards compatibility for decoration with local entity.
=> IHOST-1227 add port metric set attribute in local entity

apache-definition.yml
=> Update to protocol v3

CHANGELOG.md, tests/integration/json-schema-files/apache-schema-inventory.json, tests/integration/json-schema-files/apache-schema-metrics.json, tests/integration/json-schema-files/apache-schema.json, vendor/github.com/newrelic/infra-integrations-sdk/data/metric/metrics.go, vendor/github.com/newrelic/infra-integrations-sdk/integration/entity.go, vendor/github.com/newrelic/infra-integrations-sdk/integration/entity_id.go, vendor/github.com/newrelic/infra-integrations-sdk/integration/integration.go, vendor/vendor.json
Upgrades the sdk to the latest version
- [x ] add a risk label after carefully considering the "blast radius" of your changes
- [x ] describe the _intent_ of your changes in the description. don't just rewrite your code in prose
- [x ] assign at least one reviewer
=> [ihost-2175] Upgrade latest version of sdk

CHANGELOG.md, src/apache.go, src/status.go, src/status_test.go
Default: true. Set it to false if you have self-signed certificates
and want to avoid the integration to fail.
Clean and format the code
=> Added validate_certs configuration option

apache-config.yml.k8s_sample
Adding configuration sample for running on Kubernetes.
=> Adding Config sample for Kubernetes

CHANGELOG.md, apache-config.yml.sample, src/apache.go
Include the status_url in the inventory configuration since this is required for the entity name.
Clean and format the code
=> Updated the config sample

.github/workflows/prerelease.yml
=> ci: Add package test actions

.github/workflows/prerelease.yml, .github/workflows/push_pr.yml, .github/workflows/release.yml, CODE_OF_CONDUCT.md, build/ci.mk
=> core: add publish action

CHANGELOG.md, build/.goreleaser.yml, build/release.mk
=> ARM Support

apache-log.yml.example, build/.goreleaser.yml
=> add_apache_logs_example_yml

apache-log-win.yml.example, build/.goreleaser.yml, build/package/windows/nri-386-installer/Product.wxs, build/package/windows/nri-amd64-installer/Product.wxs, build/windows/fix_archives.sh
Add Windows logging template to apache-nri
=> Add Windows logging template to apache-nri

build/package/windows/nri-amd64-installer/Product.wxs
Add missing conifg:
`<ComponentGroupRef Id="PluginLogConfigsComponent"/>`
=> Update nri-amd64-installer Product.wxs

renovate.json
This reverts commit c3e6109cc8cb1580c6aaf700ba6b24d4fd1616fa.
=> Revert "Add renovate.json (#90)"

.github/workflows/on_release.yaml
=> [WIP] chore: use release reusable workflow

.github/workflows/on_push_pr.yaml
This PR updates the push PR workflow to use the new reusable workflow.
=> NR-211968: update push pr to a reusable workflow
